package pl.aliaksandrou.interviewee.enums;

/**
 * This enum represents the different AI models that can be used in the application.
 * Currently, it only contains one model: ChatGPT-4.
 */
public enum Language {
    ENGLISH("en"),
    CHINESE("zh"),
    SPANISH("es"),
    ARABIC("ar"),
    HINDI("hi"),
    BENGALI("bn"),
    PORTUGUESE("pt"),
    BELARUSIAN("be"),
    RUSSIAN("ru"),
    JAPANESE("ja"),
    GERMAN("de"),
    JAVANESE("jv"),
    KOREAN("ko"),
    FRENCH("fr"),
    TURKISH("tr"),
    VIETNAMESE("vi"),
    TELUGU("te"),
    MARATHI("mr"),
    TAMIL("ta"),
    URDU("ur"),
    ITALIAN("it"),
    PERSIAN("fa"),
    GUJARATI("gu"),
    POLISH("pl"),
    UKRAINIAN("uk"),
    MALAY("ms"),
    MALAYALAM("ml"),
    ORIYA("or"),
    PUNJABI("pa"),
    THAI("th"),
    DUTCH("nl"),
    BHOJPURI("bh"),
    TAGALOG("tl"),
    YORUBA("yo"),
    MAITHILI("mai"),
    UZBEK("uz"),
    SINDHI("sd"),
    AMHARIC("am"),
    FULA("ff"),
    ROMANIAN("ro"),
    OROMO("om"),
    AZERBAIJANI("az"),
    AWADHI("awa"),
    GAN("gan"),
    CEBUANO("ceb"),
    KURDISH("ku"),
    SERBO_CROATIAN("sh"),
    MALAGASY("mg"),
    SARAIKI("skr"),
    NEPALI("ne"),
    SINHALESE("si"),
    CHITTAGONIAN("ctg"),
    ZHUANG("za"),
    KHMER("km"),
    TURKMEN("tk"),
    ASSAMESE("as"),
    MADURESE("mad"),
    SOMALI("so"),
    MARWARI("mwr"),
    MAGAHI("mag"),
    HARYANVI("bgc"),
    HUNGARIAN("hu"),
    CHHATTISGARHI("hne"),
    GREEK("el"),
    CHEWA("ny"),
    DECCAN("dcc"),
    AKAN("ak"),
    KAZAKH("kk"),
    NORTHERN_MIN("cdo"),
    SUNDANESE("su"),
    KINYARWANDA("rw"),
    ZULU("zu"),
    DHUNDHARI("dhd"),
    HAITIAN_CREOLE("ht"),
    EASTERN_MIN("nan"),
    ILOCANO("ilo"),
    QUECHUA("qu"),
    KIRUNDI("rn"),
    SWEDISH("sv"),
    HMONG("hmn"),
    SHONA("sn"),
    UYGHUR("ug"),
    HILIGAYNON("hil"),
    MOSSI("mos"),
    XHOSA("xh"),
    BALOCHI("bal"),
    KONKANI("kok");

    private final String code;

    Language(String code) {
        this.code = code;
    }

    public String getCode() {
        return this.code;
    }
}
